import {
  red,
  pink,
  purple,
  deepPurple,
  indigo,
  blue,
  lightBlue,
  cyan,
  teal,
  green,
  lightGreen,
  lime,
  yellow,
  amber,
  orange,
  deepOrange,
  brown,
  blueGrey,
} from 'material-ui-colors'

export const palette: any = {
  red: red[700],
  pink: pink[500],
  purple: purple[400],
  'deep-purple': deepPurple[400],
  indigo: indigo[400],
  blue: blue[400],
  'light-blue': lightBlue[400],
  cyan: cyan[400],
  teal: teal[400],
  green: green[600],
  'light-green': lightGreen[400],
  lime: lime[400],
  yellow: yellow[500],
  amber: amber[400],
  orange: orange[400],
  'deep-orange': deepOrange[400],
  brown: brown[400],
  // 'grey': gray[500],
  'blue-grey': blueGrey[400],
}
